METS-Programme/openmrs-module-ugandaemr-sync

api/src/main/java/org/openmrs/module/ugandaemrsync/SyncTask.java, api/src/main/resources/liquibase.xml
This is to shedule the time the sync task runs
=> Adding Scheduler

api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java
https://app.asana.com/0/1133167201254938/1166146506370538
=> Catch password error is not set

api/src/main/resources/liquibase.xml
https://app.asana.com/0/1133167201254913/1175338194929346
Error starting reporting Module due to error in ugandaemrsync liquibase on id ugandaemr-20200105-0917
=> 1175338194929346:Error starting reporting Module due to error in ugandaemrsync liquibase on id ugandaemr-20200105-0917

pom.xml
https://app.asana.com/0/1133167201254913/1175976975075817
Changing dependency scope for json in Ugandaemrsync module
=> 1175976975075817:Changing dependency scope for json in Ugandaemrsync module

omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/ViralLoadUploadPageController.java
https://app.asana.com/0/1133167201254915/1182383366995771
Fix failing upload of VL results When the DHSI2 Code is set in global properties
=> Fix failing upload of VL results When the DHSI2 Code is set in global properties

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java
https://app.asana.com/0/0/1180876737528700/f
=> Review the Sync frequency and set to once a day

api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncDataRecord.java
Enable token Authentication in method  sendPostByWithBasicAuth
https://app.asana.com/0/1133167201254913/1185616775688313
=> Enable token Authentication in method  sendPostByWithBasicAuth

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/ViralLoadUploadPageController.java, omod/src/main/webapp/pages/viralLoadUpload.gsp
https://app.asana.com/0/1133167201254915/1189864148782897/f
=> Revise Manual upload of Viral Load results 

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveViralLoadResultFromCentralServerTask.java
https://app.asana.com/0/1133167201254913/1190505336548281
=> Fix failing sync of Viral Load results from CPHL

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendDHIS2DataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendRecencyDataToCentralServerTask.java
https://app.asana.com/0/1133167201254915/1193857162544577
=> Remove user alerts for authentication and configuration errors

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/ViralLoadUploadPageController.java
Change date checking to ensure it corresponds date format used in the CSV uploadedhttps://app.asana.com/0/1133167201254915/1199106973248567
In adding viral load to encounter Save group Observation with its members  instead of a whole encounter. 
https://app.asana.com/0/1133167201254915/1199106973248568
=> Change date checking to ensure it corresponds date format used in the CSV &  Save group Observation with its members  instead of a whole encounter. 

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java
https://app.asana.com/0/1133167201254915/1199218733885621
UgandaEMR Metrix  flagging off developer machines from sending data
=> UgandaEMR Metrix  flagging off developer machines from sending data

api/src/main/java/org/openmrs/module/ugandaemrsync/UgandaEMRSyncConfig.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendDHIS2DataToCentralServerTask.java
https://app.asana.com/0/1133167201254915/1199369554482109
=> Add DHIS2 UUID and HC Name in header when sending analytics

api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveViralLoadResultFromCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendViralLoadRequestToCentralServerTask.java
https://app.asana.com/0/1133167201254913/1200700943900274
Testing Approach. 
Change the URL in the UgandaEMR Sync Task Type to the testing intense. NOTE this is only for testing intense. UgandaEMR production servers at facility should be kept with the same URLs
1. **Send Viral Load To CPHL**  --->>>> https://openhimlive.cphluganda.org:5000/emrlab/send_sample?api_token=B4qoJUpu79qmNfS1zg3b9DT1WVqenUYbgeCyQfinUHiF3jILqCdiQ9p6zor8
2. **Request Viral Load Results form CPHL**  --->>>>  https://openhimlive.cphluganda.org:5000/emrlab/sample_result?api_token=B4qoJUpu79qmNfS1zg3b9DT1WVqenUYbgeCyQfinUHiF3jILqCdiQ9p6zor8
Create a Viral load request for a patient either through retrospective approach or point of care approach. 
Check the change logs to see if the requests have been sent to CPHL. …
=> Update Viral Load interpretation of viral load responses that are rendered. 

pom.xml
https://app.asana.com/0/1133167201254915/1201026099539688/f
=> Remove duplicated decencies declarations

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/test/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecordTest.java
https://app.asana.com/0/1133167201254913/1201332242626170
=> Improve identification of cases by sync Episode of Care

api/src/main/resources/liquibase.xml
Add SNOMED CT Mapping to Fhir Concept Source Table
https://app.asana.com/0/1133167201254913/1201799272216770
=> Add SNOMED CT Mapping to Fhir Concept Source Table

pom.xml
Remove dependency on guava that is flagged as a potential security issue
https://app.asana.com/0/1133167201254913/1202151788743504
=> Remove dependency on guava that is flagged as a potential security issue

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendFhirResourceTask.java
https://app.asana.com/0/1133167201254913/1203004632145167
=> Ensure birthdate is not just a year for patients with estimated age.

pom.xml
https://talk.openmrs.org/t/most-poms-configured-to-include-api-artifacts-twice-in-the-pom/35257
=> Fix inclusion of API resources twice in the pom 

api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/SentSmsPageController.java, omod/src/main/webapp/fragments/home.gsp, omod/src/main/webapp/pages/sentSms.gsp
https://app.asana.com/0/1133167201254915/1203275963708736/f
=> Viewing Sent messages at the facility in EMR

api/src/main/resources/liquibase.xml
https://app.asana.com/0/0/1204328574128063/f
=> Update HIV Infant profile

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java
fix internet connection check in syncing profiles
=> fix internet connection check in syncing profiles

api/pom.xml, api/src/main/java/org/openmrs/module/ugandaemrsync/UgandaEMRSyncConfig.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRHttpURLConnection.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRSyncService.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/mapper/Identifier.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/GetPatientsFromSHRTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendPatientsToFacilitySHRTask.java, api/src/main/resources/liquibase.xml, omod/pom.xml, omod/src/main/resources/config.xml, pom.xml
https://app.asana.com/0/1133167201254913/1204468593951932
=> Support Integration with facility based systems (eaFya)

api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/FhirEpisodeOfCareDao.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/impl/FhirEpisodeOfCareDaoImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/providers/r4/EpisodeOfCareProvider.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, pom.xml
https://metsprogramme.atlassian.net/browse/U4X-123
=> U4X-123 Update FHIR2 module to 1.9.0

api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/USM-5
=> USM-5 Add condition to ensure patient identifier of HIV Profile exists before attempting to change it

api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/UgandaEMRSyncDao.java, api/src/main/java/org/openmrs/module/ugandaemrsync/model/SyncFhirProfile.java, api/src/main/java/org/openmrs/module/ugandaemrsync/model/SyncFhirResource.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/resources/liquibase.xml, maven-settings.xml, omod/src/main/java/org/openmrs/module/ugandaemrsync/fragment/controller/SyncFhirProfileFragmentController.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/SyncFhirProfilePageController.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirProfileResource.java, omod/src/main/webapp/pages/syncFhirProfile.gsp
- USM-1 Add Status Code and status Code details to sync the resource object
-  USM-2 Limit the number of resources to sync per profile to a selected server per sync cycle
- USM-4 Delete Payload after syncing the payload to the set destination
https://metsprogramme.atlassian.net/browse/USM-4
https://metsprogramme.atlassian.net/browse/USM-2
https://metsprogramme.atlassian.net/browse/USM-1
=>  USM-1 Add Status Code and status Code details to sync fhir resource object

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, omod/src/main/webapp/pages/syncFhirProfile.gsp
https://metsprogramme.atlassian.net/browse/USM-9
=> USM-9 Add patient filter to patient fhir resource generator

api/src/main/java/org/openmrs/module/ugandaemrsync/model/SyncFhirResource.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirResourceResource.java
https://metsprogramme.atlassian.net/browse/USM-10
=> USM-10 : Add patient to syncFhirResource

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskTypeResource.java
https://metsprogramme.atlassian.net/browse/USM-11
=> USM-11 add  params to full fetch of sync task type

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/DTO/TestResultDTO.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/RecieveLabResultResource.java
https://metsprogramme.atlassian.net/browse/USM-12
=> USM-12 Change TestResult endpoint to diagnosisreport 

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/model/SyncTask.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskResource.java
https://metsprogramme.atlassian.net/browse/USM-13
=> USM-13: Add SyncTask API 

pom.xml
https://metsprogramme.atlassian.net/browse/USM-14
=> USM-14: upgrade uiframework version to 3.22.0

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java
https://metsprogramme.atlassian.net/browse/UKCB-9
=> UKCB-9:Add System to telecom

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java, api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/SyncFhirProfilePageController.java, omod/src/main/webapp/pages/syncFhirProfile.gsp
https://metsprogramme.atlassian.net/browse/USM-18
=> USM-18: add check on  addAttributeToObject to ensure that the object is available 

api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRSyncService.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/UgandaEMRSyncDao.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncConstant.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveLabResultFromALISTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveViralLoadResultFromCentralServerTask.java, api/src/test/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRSyncServiceTest.java
https://metsprogramme.atlassian.net/browse/USM-19
=> USM-19: change query of getting incomplete tests to a non join approach

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/MortalitySurveillanceTask.java, api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/CW-4
=> CW-4: Integrate Motility Surveillance with DHIS2

api/src/main/java/org/openmrs/module/ugandaemrsync/model/SyncFhirProfile.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/CrossBorderIntegrationSyncTask.java, api/src/main/resources/liquibase.xml, omod/src/main/java/org/openmrs/module/ugandaemrsync/page/controller/SyncFhirProfilePageController.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirProfileResource.java, omod/src/main/webapp/pages/syncFhirProfile.gsp
https://metsprogramme.atlassian.net/browse/USM-21
=> USM-21: Add search URL if profile is searchable

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/RecieveLabResultResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirCaseResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirProfileLogResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirProfileResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirResourceDetailsResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncFhirResourceResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskDetailsResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskTypeResource.java
https://metsprogramme.atlassian.net/browse/USM-25
=> USM-25:Upgrade endpoints in UgandaEMRSync to support platform version 2.6.4

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/USM-26
=> USM-26: Revise the generation of Cases and Resources for Sync FHIR profiles

api/pom.xml, api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveViralLoadResultFromCentralServerTask.java, api/src/test/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRSyncServiceTest.java, api/src/test/resources/org/openmrs/module/ugandaemrsync/include/standardTestDataset.xml, pom.xml
https://metsprogramme.atlassian.net/browse/USM-30
=> USM-30: Improve logging of test results response from CPHL

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java, omod/src/main/resources/config.xml
https://metsprogramme.atlassian.net/browse/USM-31
=> USM-31: Externalise a configurable base  url for querying api's internally in Java

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java
https://metsprogramme.atlassian.net/browse/USM-32
=> USM-32: change date for sync date for orders

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncConstant.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveViralLoadResultFromCentralServerTask.java, omod/src/main/resources/config.xml
https://metsprogramme.atlassian.net/browse/USM-33
=> USM-33: ensure telecom is not null before adding to it more details in fhir resource generation

api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendViralLoadProgramDataToCentralServerTask.java
https://metsprogramme.atlassian.net/browse/U4X-606 
https://metsprogramme.atlassian.net/browse/U4X-604
=> U4X-606:Remove unnecessary Print Code in the logs.

api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/USM-34
=> USM-34: Create Sync Profile for eAFYA integration.

api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/USM-35
=> USM-35: Correct change sets that fail due to checks when creating profiles

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/test/resources/org/openmrs/module/ugandaemrsync/include/standardTestDataset.xml
https://metsprogramme.atlassian.net/browse/USM-36
=> USM-36:Add Results Received Date to the VL HIE.

api/src/main/java/org/openmrs/module/ugandaemrsync/api/UgandaEMRSyncService.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/UgandaEMRSyncDao.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskResource.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskTypeResource.java, omod/src/main/webapp/pages/syncTask.gsp, omod/src/main/webapp/pages/syncTaskType.gsp
https://metsprogramme.atlassian.net/browse/USM-37
Improve UI of syctask logs in monitoring of system syncs implemented via sync task types
=> USM-37: Improve UI of syctask logs in monitoring of system syncs implemented via sync task types

api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/U4X-758
=> U4X-758: Change changeset ugandaemrsync-2024-07-10-1003 to a new ID

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncConstant.java, omod/src/main/resources/config.xml
https://metsprogramme.atlassian.net/browse/U4X-912
=> U4X-912: Improve on generation to avoid silent failure in generation of stock operation to send to eafya

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/RequestLabResultsResource.java
https://metsprogramme.atlassian.net/browse/U4X-986
=> U4X-986: Improve the receipt of results from CPHL and Improve the messaging structure.

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/ReferralOrderResource.java, pom.xml
https://metsprogramme.atlassian.net/browse/U4X-990
=> U4X-990: Improve API get Referred orders to ensure only referred orders with default status  in_progress 

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/ReferralOrderResource.java
https://metsprogramme.atlassian.net/browse/U4X-993
=> U4X-993: Current spelling for fulfiilerStatus in the API parameters

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java
https://metsprogramme.atlassian.net/browse/U4X-1001
=> U4X-1001: Add response of missing fields in task log when test is missing the VL required field.

api/src/main/java/org/openmrs/module/ugandaemrsync/api/impl/UgandaEMRSyncServiceImpl.java, api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/test/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecordTest.java, api/src/test/resources/org/openmrs/module/ugandaemrsync/include/standardTestDataset.xml
https://metsprogramme.atlassian.net/browse/U4X-1004
=> U4X-1004: Correct estimated date of birth to consider time beyond midnight

omod/src/main/java/org/openmrs/module/ugandaemrsync/web/resource/SyncTaskTypeResource.java
https://metsprogramme.atlassian.net/browse/U4X-1013
=> U4X-1013: Remove the trailing space on urlPassword

api/src/main/java/org/openmrs/module/ugandaemrsync/server/SyncFHIRRecord.java, api/src/main/resources/liquibase.xml
https://metsprogramme.atlassian.net/browse/U4X-1024
https://metsprogramme.atlassian.net/browse/U4X-1025
=> U4X-1024: Create FHIR Patient Identifier System mappings for known exchangeable identifiers

api/src/main/java/org/openmrs/module/ugandaemrsync/UgandaEMRSyncConfig.java, api/src/main/java/org/openmrs/module/ugandaemrsync/api/dao/UgandaEMRSyncDao.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/ReceiveVisitsDataFromARTAccessTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendAnalyticsDataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendDHIS2DataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendRecencyDataToCentralServerTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendReportsTask.java, api/src/main/java/org/openmrs/module/ugandaemrsync/tasks/SendSMSAppointmentTask.java, api/src/main/resources/moduleApplicationContext.xml
https://metsprogramme.atlassian.net/browse/U4X-1061
=> U4X-1061: Remove declaration of services before loading of OpenMRS service context
